Importing the libraries

In [1]:
import pandas as pd

importing the dataset

In [2]:
df = pd.read_csv("car_purhase.csv")
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
X = df.drop(['Purchased'],axis=1)
y = df['Purchased'].values

df.head(5)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [5]:
print(X_train)

     Age  EstimatedSalary
111   37            71000
7     32           150000
25    47            20000
287   48           138000
59    32           117000
..   ...              ...
96    35            25000
221   35            91000
363   42            79000
319   36            60000
203   41            71000

[280 rows x 2 columns]


In [6]:
print(X_test)

     Age  EstimatedSalary
220   41            80000
350   38           113000
342   38            65000
296   42            73000
140   19            85000
..   ...              ...
374   37            80000
47    27            54000
95    35            44000
131   33            31000
206   55           130000

[120 rows x 2 columns]


In [7]:
print(y_test)

[0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0
 0 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 0 0 1 0 0 0 0 0 1]


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Naive Bayes Classification model on the Training Set

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Predicting the Test Set Results

In [10]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

## Confusion Matrix and Accuracy

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm 

Accuracy :  0.9


array([[76,  4],
       [ 8, 32]])

In [12]:
classifier.score(X_train,y_train)

0.875

In [13]:
classifier.predict_proba(X_test)

array([[0.61445322, 0.38554678],
       [0.30816559, 0.69183441],
       [0.81309527, 0.18690473],
       [0.62829104, 0.37170896],
       [0.98154287, 0.01845713],
       [0.94217447, 0.05782553],
       [0.7198606 , 0.2801394 ],
       [0.78579842, 0.21420158],
       [0.64879533, 0.35120467],
       [0.95553888, 0.04446112],
       [0.8799116 , 0.1200884 ],
       [0.56999792, 0.43000208],
       [0.76517194, 0.23482806],
       [0.93947831, 0.06052169],
       [0.00674395, 0.99325605],
       [0.6773085 , 0.3226915 ],
       [0.84449029, 0.15550971],
       [0.88660582, 0.11339418],
       [0.12230178, 0.87769822],
       [0.98101076, 0.01898924],
       [0.91312006, 0.08687994],
       [0.45530507, 0.54469493],
       [0.10515534, 0.89484466],
       [0.96897432, 0.03102568],
       [0.93147861, 0.06852139],
       [0.92872864, 0.07127136],
       [0.73314965, 0.26685035],
       [0.43606121, 0.56393879],
       [0.94965764, 0.05034236],
       [0.98222748, 0.01777252],
       [0.

## Comparing the Real Values with Predicted Values

In [14]:
df = pd.DataFrame({'Real Values':y_test.reshape(-1), 'Predicted Values':y_pred.reshape(-1)})
df

Real Values  Predicted Values
0              0                 0
1              1                 1
2              0                 0
3              1                 0
4              0                 0
..           ...               ...
115            0                 0
116            0                 0
117            0                 0
118            0                 0
119            1                 1

[120 rows x 2 columns]